# Configuration for `cargo-release`
# See <https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md>
# Release using `cargo release --workspace`
allow-branch = [ "main" ]
shared-version = true
consolidate-commits = true
consolidate-pushes = true
